SELECT 
    c.NOME_COLABORADOR AS 'Colaborador/UF', 
    SUM(s.VALOR_PAGO) as 'Valor'
FROM 
    LOCAL_DE_TRABALHO l
JOIN 
    COLABORADORES c ON l.ID_COLABORADOR = c.ID_COLABORADOR
JOIN 
    SALARIOS s ON s.ID_COLABORADOR = c.ID_COLABORADOR
WHERE 
    DATEPART(YEAR,s.[DATA]) = 2014
GROUP BY 
    c.NOME
UNION
SELECT 
    l.UF AS 'Colaborador/UF', 
    SUM(s.VALOR_PAGO) as 'Valor'
FROM 
    LOCAL_DE_TRABALHO l
JOIN 
    COLABORADORES c ON l.ID_COLABORADOR = c.ID_COLABORADOR
JOIN 
    SALARIOS s ON s.ID_COLABORADOR = c.ID_COLABORADOR
WHERE 
    DATEPART(YEAR,s.[DATA]) = 2014
GROUP BY 
    l.UF